[package]
name = "crypto-get"
version = "0.1.0"
edition = "2021"


[dependencies]
log = "0.4.5"
serde = { version = "1.0.132", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
